[project]
name = "wedstartup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.0.2",
    "langchain-google-genai>=3.0.0",
    "openpyxl>=3.1.5",
    "streamlit>=1.50.0",
]
